server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8888


spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp




  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usan?serverTimezone=Asia/Seoul
    username: chaerin
    password: 0408cofls

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
